name: range_collection
description: A collection library for range.
version: 0.1.0
author: Kwang Yul Seo <kwangyul.seo@gmail.com>
homepage: https://github.com/kseo/range_collection

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  interval_skip_list: ">=0.0.3 <0.1.0"
  quiver_check: '>=1.0.0-dev.1<1.1.0'
  quiver_iterables: '>=1.0.0-dev.1<1.1.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
